### ISSUE TITLE
Problema al leer archivos .config 

### ISSUE THREAD

**Issue by ornellaolivastri** [sisoputnfrba/foro#2088]
Durante la resolución del tp0 me ocurrió que al intentar abrir con Eclipse el archivo .config, me apareció un cartel avisando de que para leer correctamente el archivo debía instalar una extensión. Como pensé que esto era necesario, seguí los pasos de esa instalación y posteriormente intenté de nuevo abrir el archivo. Allí me encontré con lo siguiente:
- Me abre el explorador de archivos y me pide que elija archivos con extensiones diferentes a las .config
- Como no elijo ninguna, ya que no aparece el archivo que necesito, llego a esto:
![image](https://user-images.githubusercontent.com/63430439/118560951-ae993c00-b740-11eb-8459-39dd3473912d.png)
**Como observación, puedo abrir los archivos .config por fuera de eclipse sin ningun problema, pero temo que ésta extensión genere otros problemas además de éste, por lo cual intenté desinstalarla, por las dudas.**
Para eso investigué en google cómo desinstalar plugins de Eclipse, y lo primero que encontré fue esto:
fuente: https://www.discoduroderoer.es/instalar-y-desinstalar-plugins-en-eclipse/ 
"Para desinstalar plugins con MarketPlace haremos lo siguiente:
Abrimos Eclipse.
Pinchamos en Help -> Eclipse MarketPlace -> Installed.
Buscamos el plugin que queremos desinstalar.
Pinchamos en Uninstall.
Aceptamos que queremos desinstalarlo.
Cuando termine nos pedirá que reiniciemos el programa."

Eso solo me sirvió para poder ver los plugins instalados (aparentemente solo 1 del marketplace llamado FeatureIDE 3.6.3), ya que no me encontré con ningun botón de "uninstall":

![image](https://user-images.githubusercontent.com/63430439/118562886-f53c6580-b743-11eb-81dc-94ca808296b7.png)

Entonces continué buscando y llegué a este video: https://www.youtube.com/watch?v=cLqX3947DLk 
Seguí los pasos indicados allí y desinstalé todo lo que tenía relacionado al FeatureIDE (eran 3), y me quedó esto: 

![image](https://user-images.githubusercontent.com/63430439/118563110-59f7c000-b744-11eb-903f-1b5fb46b5169.png)

Sin embargo, el problema para leer los archivos continúa igual.

### 📦 Especificaciones de la VM
- Versión de VirtualBox: Versión 5.2.44 r139111 (Qt5.6.2)
- Memoria RAM asignada: 2 GB

### 🖥️ Especificaciones del host
- Sistema Operativo y versión: Windows10 Pro
- Memoria RAM: 4 GB
- Procesador: Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz   2.40 GHz

### 💻 Logs
Error del eclipse:
```
java.lang.NullPointerException
	at de.ovgu.featureide.fm.ui.editors.configuration.ConfigurationTreeEditorPage.createPartControl(ConfigurationTreeEditorPage.java:473)
	at org.eclipse.ui.part.MultiPageEditorPart.addPage(MultiPageEditorPart.java:241)
	at org.eclipse.ui.part.MultiPageEditorPart.addPage(MultiPageEditorPart.java:211)
	at de.ovgu.featureide.fm.ui.editors.configuration.ConfigurationEditor.initPage(ConfigurationEditor.java:424)
	at de.ovgu.featureide.fm.ui.editors.configuration.ConfigurationEditor.createPages(ConfigurationEditor.java:377)
	at org.eclipse.ui.part.MultiPageEditorPart.createPartControl(MultiPageEditorPart.java:348)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.createPartControl(CompatibilityPart.java:151)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityEditor.createPartControl(CompatibilityEditor.java:99)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:355)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:990)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:955)
	at org.eclipse.e4.core.internal.di.InjectorImpl.inject(InjectorImpl.java:124)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:399)
	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:318)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:162)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.createFromBundle(ReflectionContributionFactory.java:105)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.doCreate(ReflectionContributionFactory.java:74)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.create(ReflectionContributionFactory.java:56)
	at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer.createWidget(ContributedPartRenderer.java:129)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:992)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:661)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:767)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$0(PartRenderingEngine.java:738)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:732)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
```

Lo que me muestra la ventana de error:
![image](https://user-images.githubusercontent.com/63430439/118563913-caeba780-b745-11eb-9c22-728429d0fb30.png)
![image](https://user-images.githubusercontent.com/63430439/118563966-dccd4a80-b745-11eb-86f9-1b344e17645e.png)
![image](https://user-images.githubusercontent.com/63430439/118564019-f373a180-b745-11eb-8eab-d031f8f11511.png)

**Comment by iago64** [comment]
Buenas! como va?

El problema que estas teniendo es simplemente que seguiste la recomendación de eclipse y le agregaste un plugin a una versión de eclipse que esta bastante vieja (porque es de 32 bits y deprecaron el soporte para los 32 bits).

Los archivos de config son archivos de texto que deberías poder editarlos sin inconvenientes, generalmente los plugins de eclipse lo que hacen es remarcar la sintaxis peero que como estos configs son algo armado por nosotros no tienen una sintaxis reconocida por los plugins y bueno... explota :(

Lo que te recomiendo es que bajes de nuevo la VM para tener eclipse limpio y no le agregues un plugin extra, de última los configs son simples y los podes editar en cualquier editor de texto (vscode o gedit creo que viene en la vm)

Saludos.-

**Comment by iago64** [comment]
@ornellaolivastri como va? seguís con los inconvenientes?

**Comment by ornellaolivastri** [comment]
Buenas! Recién leo la respuesta. Voy a probar eso entonces.. seguramente así se resuelva. Muchas gracias

**Comment by iago64** [comment]
@ornellaolivastri alguna novedad? salió andando o seguís con los inconvenientes?

**Comment by iago64** [comment]
Buenas! cerramos este tema por inactividad y falta de respuestas, cualquier cosa lo reabren :)

**Comment by ornellaolivastri** [comment]
Si! Muchas gracias!!
